site_name: Skillmatrix
site_url: https://skillmatrix.ru
site_author: Alexey Pleskach
site_description: Библиотека честного опыта

repo_url: https://github.com/pleskachavkz-hue/skillmatrix
repo_name: skillmatrix

theme:
  name: material
  language: ru
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - search.highlight
    - search.suggest
  
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Светлая
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Тёмная
  
  font:
    text: Roboto
    code: Roboto Mono
  
  favicon: assets/favicon.png
  icon:
    logo: material/library

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pleskachavkz-hue
    - icon: fontawesome/brands/telegram
      link: https://t.me/UsefulMistakes
      

# extra_css:
#   - stylesheets/extra.css

nav:
  - Главная: index.md
  - CRM:
    - Почему маркетинг не про рекламу: crm/why-marketing.md
    - Где находится CRM-маркетинг: crm/customer-journey.md
    - CRM и Email-маркетинг под ключ: crm/offer.md
    - Почему я занимаюсь CRM-маркетингом: crm/why-me.md
    - Путь клиента: crm/path.md
    - Что такое CRM-маркетинг: crm/what-is.md
  - Про жизнь: life/not-work.md
  - Про музыку: music/simple.md
  - Про ремонт: repair/mirror.md
  - Про технологии: technology/how-it-works.md